services:
  # API Server
  - type: web
    name: api-server
    env: docker
    dockerfilePath: ../../backend/Dockerfile
    buildCommand: "/bin/sh -c 'alembic upgrade head && echo \"Starting Danswer Api Server\"'"
    envVars:
      - key: AUTH_TYPE
        value: "google_oauth" # Default value, can be overridden in Render's environment settings
      - key: POSTGRES_HOST
        value: "relational-db" # Assuming this is the correct host within Render's environment
      - key: VESPA_HOST
        value: "index-service" # Assuming this is the correct service name within Render's environment

  # Background Service
  - type: worker
    name: background-service
    env: docker
    dockerfilePath: ../../backend/Dockerfile
    envVars:
      - key: AUTH_TYPE
        value: "google_oauth"
      - key: POSTGRES_HOST
        value: "relational-db"
      - key: VESPA_HOST
        value: "index-service"

  # Web Server
  - type: web
    name: web-server
    env: docker
    dockerfilePath: ../../web/Dockerfile
    envVars:
      - key: INTERNAL_URL
        value: "http://api-server:8080"
      - key: NEXT_PUBLIC_DISABLE_STREAMING
        value: "false" # Default value, can be overridden in Render's environment settings

  # # Relational Database (Postgres)
  # - type: postgres
  #   name: relational-db
  #   version: 15.2

  # Vespa Service
  - type: web
    name: vespa
    env: docker
    dockerfilePath: ../../vespa/Dockerfile

  # Nginx
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ../data/nginx/Dockerfile

  # Certbot
  - type: cron
    name: certbot
    schedule: "@daily"
    env: docker
    dockerfilePath: ../data/certbot/Dockerfile

  # Model Server
  - type: web
    name: model-server
    env: docker
    dockerfilePath: ../../backend/Dockerfile.model_server
    envVars:
      - key: DOCUMENT_ENCODER_MODEL
        value: "${DOCUMENT_ENCODER_MODEL:-default_value}" # Replace 'default_value' as needed
      - key: NORMALIZE_EMBEDDINGS
        value: "${NORMALIZE_EMBEDDINGS:-default_value}"
      - key: MIN_THREADS_ML_MODELS
        value: "${MIN_THREADS_ML_MODELS:-default_value}"
      - key: LOG_LEVEL
        value: "${LOG_LEVEL:-info}"
